version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    funlen:
      lines: 70
      statements: 50
    gocritic:
      enabled-tags:
        - style
        - experimental
        - performance
        - diagnostic
        - opinionated
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test.go
      - linters:
          - gocritic
        path: _test.go
        text: 'hugeParam\: \S+ is heavy \(\d+ bytes\)\; consider passing it by pointer'
    paths:
      - /home/z0tedd/Documents/go-z0tedd/pgdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/central-university-dev/go-z0tedd
  exclusions:
    generated: lax
    paths:
      - /home/z0tedd/Documents/go-z0tedd/pgdata
      - third_party$
      - builtin$
      - examples$
