with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  # github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/bot_api/client:
  #   config:
  #     dir: pkg/mocks
  #   interfaces:
  #     ClientWithResponsesInterface:
  github.com/central-university-dev/go-z0tedd/internal/application/scrapper/notification:
    config:
      dir: pkg/mocks/scrapper/notification
      outpkg: notification
    interfaces:
      Sender:

  github.com/central-university-dev/go-z0tedd/internal/infrastructure/http/common:
    config:
      dir: pkg/mocks/common
      outpkg: mockHTTPRequestDoer
    interfaces:
      HTTPRequestDoer:

  github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/github:
    config:
      dir: pkg/mocks/github
      outpkg: mockGithub
    interfaces:
      ClientWithResponsesInterface:

  github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/stackoverflow:
    config:
      dir: pkg/mocks/stackoverflow
      outpkg: mockStackOverflow
    interfaces:
      ClientWithResponsesInterface:

  github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/bot_api/client:
    config:
      dir: pkg/mocks/bot_api/client
      outpkg: mockBotClient
    interfaces:
      ClientWithResponsesInterface:

  github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/scrapper/client:
    config:
      dir: pkg/mocks/scrapper/client
      outpkg: mockScrapperClient
    interfaces:
      ClientInterface:

  github.com/central-university-dev/go-z0tedd/internal/infrastructure/repository:
    config:
      dir: pkg/mocks/repository
      outpkg: mockRepository
    interfaces:
      Repository:
