services:
  postgres:
    image: postgres:latest

    container_name: postgres_container

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - postgres-network

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29

    profiles: ["migrations"]
    depends_on:
      - postgres
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres_container:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER} #postgres_user
      - --password=${POSTGRES_PASSWORD} #postgres_password
      # - clear-checksums
      # - rollbackCount 1
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - postgres-network

  #Я не использовал acl файл
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/dаta:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    command:
      [
        "bash",
        "-c",
        "/etc/confluent/docker/run >/log/stdout.log 2>/log/stderr.log",
      ]
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/log:/log
    networks:
      - kafka-network

  grafana:
    user: "root"
    depends_on:
      - postgres
    image: "grafana/grafana-oss:latest"
    ports:
      - 2005:3000
    volumes:
      # touch ./grafana/config/grafana.ini;
      # mkdir -p ./grafana/{config,data};
      - ./grafana/config:/etc/grafana
      - ./grafana/data:/var/lib/grafana
    environment:
      # Uncomment GF_SERVER_DOMAIN, GF_SERVER_ROOT_URL for using reserve proxy
      #GF_SERVER_DOMAIN: "grafana.domain.example" # change "grafana.domain.example" to your domain
      #GF_SERVER_ROOT_URL: "https://grafana.domain.example/" # change "grafana.domain.example" to your domain
      # GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8081/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
      # GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
      GF_LOG_FILTERS: "rendering:debug"
      # Uncomment for using PostgreSQL (recommended) instead SQLite
      GF_DATABASE_TYPE: "postgres"
      GF_DATABASE_HOST: "postgres:5432" # change "postgres:5432" to your PostgreSQL database host and port
      GF_DATABASE_NAME: ${POSTGRES_DB} # change "postgres" to your database name
      GF_DATABASE_USER: ${POSTGRES_USER} # change "postgres" to your database user name
      GF_DATABASE_PASSWORD: ${POSTGRES_PASSWORD} # change "postgres" to your database password # or use GF_DATABASE_PASSWORD
      #GF_DATABASE_PASSWORD__FILE: "/run/secrets/grafana_database_password" # for docker secrets # or use GF_DATABASE_PASSWORD
      #GF_DATABASE_SSL_MODE: "disable"
    # Uncomment for using docker secrets
    #secrets:
    #  - grafana_database_password
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   update_config:
    #     order: stop-first
    #   resources:
    #     limits:
    #       memory: 1024M
    #
    networks:
      - postgres-network
      - prometheus-network
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - 9090:9090
    volumes:
      # touch /mnt/common_volume/swarm/grafana/config/{prometheus.yaml,web-config.yaml};
      # mkdir -p /mnt/common_volume/grafana/prometheus-data
      - ./prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus/data:/prometheus
    user: "root"
    # Uncomment for using docker secrets
    #secrets:
    #  - node_exporter_password
    #  - grafana_prometheus_password
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.retention.time=7d"
    networks:
      - prometheus-network
  node-exporter:
    image: prom/node-exporter
    networks:
      - prometheus-network
    ports:
      - 9100:9100
volumes:
  .pgdata:
    driver: local
  pgadmin-data:
    driver: local
networks:
  kafka-network:
    # driver: host
  postgres-network:
    # driver: bridge
  prometheus-network:
