// Code generated by mockery v2.52.4. DO NOT EDIT.

package mockGithub

import (
	context "context"

	client "github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/github"

	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

type ClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientWithResponsesInterface) EXPECT() *ClientWithResponsesInterface_Expecter {
	return &ClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetReposOwnerRepoActivityWithResponse provides a mock function with given fields: ctx, owner, repo, reqEditors
func (_m *ClientWithResponsesInterface) GetReposOwnerRepoActivityWithResponse(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn) (*client.GetReposOwnerRepoActivityResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, owner, repo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetReposOwnerRepoActivityWithResponse")
	}

	var r0 *client.GetReposOwnerRepoActivityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoActivityResponse, error)); ok {
		return rf(ctx, owner, repo, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.GetReposOwnerRepoActivityResponse); ok {
		r0 = rf(ctx, owner, repo, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetReposOwnerRepoActivityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, owner, repo, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReposOwnerRepoActivityWithResponse'
type ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call struct {
	*mock.Call
}

// GetReposOwnerRepoActivityWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetReposOwnerRepoActivityWithResponse(ctx interface{}, owner interface{}, repo interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call {
	return &ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call{Call: _e.mock.On("GetReposOwnerRepoActivityWithResponse",
		append([]interface{}{ctx, owner, repo}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call) Run(run func(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call) Return(_a0 *client.GetReposOwnerRepoActivityResponse, _a1 error) *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoActivityResponse, error)) *ClientWithResponsesInterface_GetReposOwnerRepoActivityWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetReposOwnerRepoCommitsWithResponse provides a mock function with given fields: ctx, owner, repo, reqEditors
func (_m *ClientWithResponsesInterface) GetReposOwnerRepoCommitsWithResponse(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn) (*client.GetReposOwnerRepoCommitsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, owner, repo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetReposOwnerRepoCommitsWithResponse")
	}

	var r0 *client.GetReposOwnerRepoCommitsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoCommitsResponse, error)); ok {
		return rf(ctx, owner, repo, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.GetReposOwnerRepoCommitsResponse); ok {
		r0 = rf(ctx, owner, repo, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetReposOwnerRepoCommitsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, owner, repo, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReposOwnerRepoCommitsWithResponse'
type ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call struct {
	*mock.Call
}

// GetReposOwnerRepoCommitsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetReposOwnerRepoCommitsWithResponse(ctx interface{}, owner interface{}, repo interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call {
	return &ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call{Call: _e.mock.On("GetReposOwnerRepoCommitsWithResponse",
		append([]interface{}{ctx, owner, repo}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call) Run(run func(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call) Return(_a0 *client.GetReposOwnerRepoCommitsResponse, _a1 error) *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoCommitsResponse, error)) *ClientWithResponsesInterface_GetReposOwnerRepoCommitsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetReposOwnerRepoWithResponse provides a mock function with given fields: ctx, owner, repo, reqEditors
func (_m *ClientWithResponsesInterface) GetReposOwnerRepoWithResponse(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn) (*client.GetReposOwnerRepoResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, owner, repo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetReposOwnerRepoWithResponse")
	}

	var r0 *client.GetReposOwnerRepoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoResponse, error)); ok {
		return rf(ctx, owner, repo, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.RequestEditorFn) *client.GetReposOwnerRepoResponse); ok {
		r0 = rf(ctx, owner, repo, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetReposOwnerRepoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, owner, repo, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReposOwnerRepoWithResponse'
type ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call struct {
	*mock.Call
}

// GetReposOwnerRepoWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetReposOwnerRepoWithResponse(ctx interface{}, owner interface{}, repo interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call {
	return &ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call{Call: _e.mock.On("GetReposOwnerRepoWithResponse",
		append([]interface{}{ctx, owner, repo}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call) Run(run func(ctx context.Context, owner string, repo string, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call) Return(_a0 *client.GetReposOwnerRepoResponse, _a1 error) *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call) RunAndReturn(run func(context.Context, string, string, ...client.RequestEditorFn) (*client.GetReposOwnerRepoResponse, error)) *ClientWithResponsesInterface_GetReposOwnerRepoWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersUsernameReposWithResponse provides a mock function with given fields: ctx, username, reqEditors
func (_m *ClientWithResponsesInterface) GetUsersUsernameReposWithResponse(ctx context.Context, username string, reqEditors ...client.RequestEditorFn) (*client.GetUsersUsernameReposResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, username)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersUsernameReposWithResponse")
	}

	var r0 *client.GetUsersUsernameReposResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetUsersUsernameReposResponse, error)); ok {
		return rf(ctx, username, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetUsersUsernameReposResponse); ok {
		r0 = rf(ctx, username, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetUsersUsernameReposResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, username, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersUsernameReposWithResponse'
type ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call struct {
	*mock.Call
}

// GetUsersUsernameReposWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetUsersUsernameReposWithResponse(ctx interface{}, username interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call {
	return &ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call{Call: _e.mock.On("GetUsersUsernameReposWithResponse",
		append([]interface{}{ctx, username}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call) Run(run func(ctx context.Context, username string, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call) Return(_a0 *client.GetUsersUsernameReposResponse, _a1 error) *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetUsersUsernameReposResponse, error)) *ClientWithResponsesInterface_GetUsersUsernameReposWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersUsernameWithResponse provides a mock function with given fields: ctx, username, reqEditors
func (_m *ClientWithResponsesInterface) GetUsersUsernameWithResponse(ctx context.Context, username string, reqEditors ...client.RequestEditorFn) (*client.GetUsersUsernameResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, username)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersUsernameWithResponse")
	}

	var r0 *client.GetUsersUsernameResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetUsersUsernameResponse, error)); ok {
		return rf(ctx, username, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetUsersUsernameResponse); ok {
		r0 = rf(ctx, username, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetUsersUsernameResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, username, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersUsernameWithResponse'
type ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call struct {
	*mock.Call
}

// GetUsersUsernameWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetUsersUsernameWithResponse(ctx interface{}, username interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call {
	return &ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call{Call: _e.mock.On("GetUsersUsernameWithResponse",
		append([]interface{}{ctx, username}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call) Run(run func(ctx context.Context, username string, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call) Return(_a0 *client.GetUsersUsernameResponse, _a1 error) *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call) RunAndReturn(run func(context.Context, string, ...client.RequestEditorFn) (*client.GetUsersUsernameResponse, error)) *ClientWithResponsesInterface_GetUsersUsernameWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
