// Code generated by mockery v2.52.4. DO NOT EDIT.

package mockScrapperClient

import (
	context "context"

	client "github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/scrapper/client"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

type ClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientWithResponsesInterface) EXPECT() *ClientWithResponsesInterface_Expecter {
	return &ClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// DeleteLinksWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *ClientWithResponsesInterface) DeleteLinksWithResponse(ctx context.Context, params *client.DeleteLinksParams, reqEditors ...client.RequestEditorFn) (*client.DeleteLinksResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLinksWithResponse")
	}

	var r0 *client.DeleteLinksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) (*client.DeleteLinksResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) *client.DeleteLinksResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteLinksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_DeleteLinksWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLinksWithResponse'
type ClientWithResponsesInterface_DeleteLinksWithResponse_Call struct {
	*mock.Call
}

// DeleteLinksWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.DeleteLinksParams
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) DeleteLinksWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_DeleteLinksWithResponse_Call {
	return &ClientWithResponsesInterface_DeleteLinksWithResponse_Call{Call: _e.mock.On("DeleteLinksWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_DeleteLinksWithResponse_Call) Run(run func(ctx context.Context, params *client.DeleteLinksParams, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_DeleteLinksWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.DeleteLinksParams), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_DeleteLinksWithResponse_Call) Return(_a0 *client.DeleteLinksResponse, _a1 error) *ClientWithResponsesInterface_DeleteLinksWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_DeleteLinksWithResponse_Call) RunAndReturn(run func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) (*client.DeleteLinksResponse, error)) *ClientWithResponsesInterface_DeleteLinksWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTgChatIdWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *ClientWithResponsesInterface) DeleteTgChatIdWithResponse(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn) (*client.DeleteTgChatIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTgChatIdWithResponse")
	}

	var r0 *client.DeleteTgChatIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) (*client.DeleteTgChatIdResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) *client.DeleteTgChatIdResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteTgChatIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTgChatIdWithResponse'
type ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call struct {
	*mock.Call
}

// DeleteTgChatIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) DeleteTgChatIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call {
	return &ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call{Call: _e.mock.On("DeleteTgChatIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call) Run(run func(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call) Return(_a0 *client.DeleteTgChatIdResponse, _a1 error) *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...client.RequestEditorFn) (*client.DeleteTgChatIdResponse, error)) *ClientWithResponsesInterface_DeleteTgChatIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinksWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *ClientWithResponsesInterface) GetLinksWithResponse(ctx context.Context, params *client.GetLinksParams, reqEditors ...client.RequestEditorFn) (*client.GetLinksResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLinksWithResponse")
	}

	var r0 *client.GetLinksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) (*client.GetLinksResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) *client.GetLinksResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetLinksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetLinksWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinksWithResponse'
type ClientWithResponsesInterface_GetLinksWithResponse_Call struct {
	*mock.Call
}

// GetLinksWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.GetLinksParams
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetLinksWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetLinksWithResponse_Call {
	return &ClientWithResponsesInterface_GetLinksWithResponse_Call{Call: _e.mock.On("GetLinksWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetLinksWithResponse_Call) Run(run func(ctx context.Context, params *client.GetLinksParams, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_GetLinksWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.GetLinksParams), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetLinksWithResponse_Call) Return(_a0 *client.GetLinksResponse, _a1 error) *ClientWithResponsesInterface_GetLinksWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetLinksWithResponse_Call) RunAndReturn(run func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) (*client.GetLinksResponse, error)) *ClientWithResponsesInterface_GetLinksWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostLinksWithBodyWithResponse provides a mock function with given fields: ctx, params, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) PostLinksWithBodyWithResponse(ctx context.Context, params *client.PostLinksParams, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn) (*client.PostLinksResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostLinksWithBodyWithResponse")
	}

	var r0 *client.PostLinksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) (*client.PostLinksResponse, error)); ok {
		return rf(ctx, params, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) *client.PostLinksResponse); ok {
		r0 = rf(ctx, params, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostLinksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostLinksWithBodyWithResponse'
type ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostLinksWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.PostLinksParams
//   - contentType string
//   - body io.Reader
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) PostLinksWithBodyWithResponse(ctx interface{}, params interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call {
	return &ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call{Call: _e.mock.On("PostLinksWithBodyWithResponse",
		append([]interface{}{ctx, params, contentType, body}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call) Run(run func(ctx context.Context, params *client.PostLinksParams, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.PostLinksParams), args[2].(string), args[3].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call) Return(_a0 *client.PostLinksResponse, _a1 error) *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call) RunAndReturn(run func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) (*client.PostLinksResponse, error)) *ClientWithResponsesInterface_PostLinksWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostLinksWithResponse provides a mock function with given fields: ctx, params, body, reqEditors
func (_m *ClientWithResponsesInterface) PostLinksWithResponse(ctx context.Context, params *client.PostLinksParams, body client.AddLinkRequest, reqEditors ...client.RequestEditorFn) (*client.PostLinksResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostLinksWithResponse")
	}

	var r0 *client.PostLinksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) (*client.PostLinksResponse, error)); ok {
		return rf(ctx, params, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) *client.PostLinksResponse); ok {
		r0 = rf(ctx, params, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostLinksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_PostLinksWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostLinksWithResponse'
type ClientWithResponsesInterface_PostLinksWithResponse_Call struct {
	*mock.Call
}

// PostLinksWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.PostLinksParams
//   - body client.AddLinkRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) PostLinksWithResponse(ctx interface{}, params interface{}, body interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_PostLinksWithResponse_Call {
	return &ClientWithResponsesInterface_PostLinksWithResponse_Call{Call: _e.mock.On("PostLinksWithResponse",
		append([]interface{}{ctx, params, body}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_PostLinksWithResponse_Call) Run(run func(ctx context.Context, params *client.PostLinksParams, body client.AddLinkRequest, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_PostLinksWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.PostLinksParams), args[2].(client.AddLinkRequest), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_PostLinksWithResponse_Call) Return(_a0 *client.PostLinksResponse, _a1 error) *ClientWithResponsesInterface_PostLinksWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_PostLinksWithResponse_Call) RunAndReturn(run func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) (*client.PostLinksResponse, error)) *ClientWithResponsesInterface_PostLinksWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostTgChatIdWithResponse provides a mock function with given fields: ctx, id, reqEditors
func (_m *ClientWithResponsesInterface) PostTgChatIdWithResponse(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn) (*client.PostTgChatIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostTgChatIdWithResponse")
	}

	var r0 *client.PostTgChatIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) (*client.PostTgChatIdResponse, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) *client.PostTgChatIdResponse); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostTgChatIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_PostTgChatIdWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTgChatIdWithResponse'
type ClientWithResponsesInterface_PostTgChatIdWithResponse_Call struct {
	*mock.Call
}

// PostTgChatIdWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) PostTgChatIdWithResponse(ctx interface{}, id interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call {
	return &ClientWithResponsesInterface_PostTgChatIdWithResponse_Call{Call: _e.mock.On("PostTgChatIdWithResponse",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call) Run(run func(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call) Return(_a0 *client.PostTgChatIdResponse, _a1 error) *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call) RunAndReturn(run func(context.Context, int64, ...client.RequestEditorFn) (*client.PostTgChatIdResponse, error)) *ClientWithResponsesInterface_PostTgChatIdWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
