// Code generated by mockery v2.52.4. DO NOT EDIT.

package mockScrapperClient

import (
	context "context"

	client "github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/scrapper/client"

	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

type ClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientInterface) EXPECT() *ClientInterface_Expecter {
	return &ClientInterface_Expecter{mock: &_m.Mock}
}

// DeleteLinks provides a mock function with given fields: ctx, params, reqEditors
func (_m *ClientInterface) DeleteLinks(ctx context.Context, params *client.DeleteLinksParams, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLinks")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_DeleteLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLinks'
type ClientInterface_DeleteLinks_Call struct {
	*mock.Call
}

// DeleteLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.DeleteLinksParams
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) DeleteLinks(ctx interface{}, params interface{}, reqEditors ...interface{}) *ClientInterface_DeleteLinks_Call {
	return &ClientInterface_DeleteLinks_Call{Call: _e.mock.On("DeleteLinks",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *ClientInterface_DeleteLinks_Call) Run(run func(ctx context.Context, params *client.DeleteLinksParams, reqEditors ...client.RequestEditorFn)) *ClientInterface_DeleteLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.DeleteLinksParams), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_DeleteLinks_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_DeleteLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_DeleteLinks_Call) RunAndReturn(run func(context.Context, *client.DeleteLinksParams, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_DeleteLinks_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTgChatId provides a mock function with given fields: ctx, id, reqEditors
func (_m *ClientInterface) DeleteTgChatId(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTgChatId")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_DeleteTgChatId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTgChatId'
type ClientInterface_DeleteTgChatId_Call struct {
	*mock.Call
}

// DeleteTgChatId is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) DeleteTgChatId(ctx interface{}, id interface{}, reqEditors ...interface{}) *ClientInterface_DeleteTgChatId_Call {
	return &ClientInterface_DeleteTgChatId_Call{Call: _e.mock.On("DeleteTgChatId",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *ClientInterface_DeleteTgChatId_Call) Run(run func(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn)) *ClientInterface_DeleteTgChatId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_DeleteTgChatId_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_DeleteTgChatId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_DeleteTgChatId_Call) RunAndReturn(run func(context.Context, int64, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_DeleteTgChatId_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinks provides a mock function with given fields: ctx, params, reqEditors
func (_m *ClientInterface) GetLinks(ctx context.Context, params *client.GetLinksParams, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLinks")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_GetLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinks'
type ClientInterface_GetLinks_Call struct {
	*mock.Call
}

// GetLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.GetLinksParams
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) GetLinks(ctx interface{}, params interface{}, reqEditors ...interface{}) *ClientInterface_GetLinks_Call {
	return &ClientInterface_GetLinks_Call{Call: _e.mock.On("GetLinks",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *ClientInterface_GetLinks_Call) Run(run func(ctx context.Context, params *client.GetLinksParams, reqEditors ...client.RequestEditorFn)) *ClientInterface_GetLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.GetLinksParams), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_GetLinks_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_GetLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_GetLinks_Call) RunAndReturn(run func(context.Context, *client.GetLinksParams, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_GetLinks_Call {
	_c.Call.Return(run)
	return _c
}

// PostLinks provides a mock function with given fields: ctx, params, body, reqEditors
func (_m *ClientInterface) PostLinks(ctx context.Context, params *client.PostLinksParams, body client.AddLinkRequest, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostLinks")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, params, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, params, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostLinks'
type ClientInterface_PostLinks_Call struct {
	*mock.Call
}

// PostLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.PostLinksParams
//   - body client.AddLinkRequest
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) PostLinks(ctx interface{}, params interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostLinks_Call {
	return &ClientInterface_PostLinks_Call{Call: _e.mock.On("PostLinks",
		append([]interface{}{ctx, params, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostLinks_Call) Run(run func(ctx context.Context, params *client.PostLinksParams, body client.AddLinkRequest, reqEditors ...client.RequestEditorFn)) *ClientInterface_PostLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.PostLinksParams), args[2].(client.AddLinkRequest), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostLinks_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostLinks_Call) RunAndReturn(run func(context.Context, *client.PostLinksParams, client.AddLinkRequest, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostLinks_Call {
	_c.Call.Return(run)
	return _c
}

// PostLinksWithBody provides a mock function with given fields: ctx, params, contentType, body, reqEditors
func (_m *ClientInterface) PostLinksWithBody(ctx context.Context, params *client.PostLinksParams, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostLinksWithBody")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, params, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, params, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostLinksWithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostLinksWithBody'
type ClientInterface_PostLinksWithBody_Call struct {
	*mock.Call
}

// PostLinksWithBody is a helper method to define mock.On call
//   - ctx context.Context
//   - params *client.PostLinksParams
//   - contentType string
//   - body io.Reader
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) PostLinksWithBody(ctx interface{}, params interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostLinksWithBody_Call {
	return &ClientInterface_PostLinksWithBody_Call{Call: _e.mock.On("PostLinksWithBody",
		append([]interface{}{ctx, params, contentType, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostLinksWithBody_Call) Run(run func(ctx context.Context, params *client.PostLinksParams, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn)) *ClientInterface_PostLinksWithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*client.PostLinksParams), args[2].(string), args[3].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostLinksWithBody_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostLinksWithBody_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostLinksWithBody_Call) RunAndReturn(run func(context.Context, *client.PostLinksParams, string, io.Reader, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostLinksWithBody_Call {
	_c.Call.Return(run)
	return _c
}

// PostTgChatId provides a mock function with given fields: ctx, id, reqEditors
func (_m *ClientInterface) PostTgChatId(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostTgChatId")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, id, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...client.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, id, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, id, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostTgChatId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTgChatId'
type ClientInterface_PostTgChatId_Call struct {
	*mock.Call
}

// PostTgChatId is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientInterface_Expecter) PostTgChatId(ctx interface{}, id interface{}, reqEditors ...interface{}) *ClientInterface_PostTgChatId_Call {
	return &ClientInterface_PostTgChatId_Call{Call: _e.mock.On("PostTgChatId",
		append([]interface{}{ctx, id}, reqEditors...)...)}
}

func (_c *ClientInterface_PostTgChatId_Call) Run(run func(ctx context.Context, id int64, reqEditors ...client.RequestEditorFn)) *ClientInterface_PostTgChatId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostTgChatId_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostTgChatId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostTgChatId_Call) RunAndReturn(run func(context.Context, int64, ...client.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostTgChatId_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
