// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/central-university-dev/go-z0tedd/internal/api/openapi/v1/bot_api/client"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

type ClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientWithResponsesInterface) EXPECT() *ClientWithResponsesInterface_Expecter {
	return &ClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// PostUpdatesWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) PostUpdatesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn) (*client.PostUpdatesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostUpdatesWithBodyWithResponse")
	}

	var r0 *client.PostUpdatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...client.RequestEditorFn) (*client.PostUpdatesResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...client.RequestEditorFn) *client.PostUpdatesResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostUpdatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUpdatesWithBodyWithResponse'
type ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostUpdatesWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) PostUpdatesWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call {
	return &ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call{Call: _e.mock.On("PostUpdatesWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call) Return(_a0 *client.PostUpdatesResponse, _a1 error) *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call) RunAndReturn(run func(context.Context, string, io.Reader, ...client.RequestEditorFn) (*client.PostUpdatesResponse, error)) *ClientWithResponsesInterface_PostUpdatesWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostUpdatesWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientWithResponsesInterface) PostUpdatesWithResponse(ctx context.Context, body client.LinkUpdate, reqEditors ...client.RequestEditorFn) (*client.PostUpdatesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostUpdatesWithResponse")
	}

	var r0 *client.PostUpdatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.LinkUpdate, ...client.RequestEditorFn) (*client.PostUpdatesResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.LinkUpdate, ...client.RequestEditorFn) *client.PostUpdatesResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PostUpdatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.LinkUpdate, ...client.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_PostUpdatesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUpdatesWithResponse'
type ClientWithResponsesInterface_PostUpdatesWithResponse_Call struct {
	*mock.Call
}

// PostUpdatesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body client.LinkUpdate
//   - reqEditors ...client.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) PostUpdatesWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_PostUpdatesWithResponse_Call {
	return &ClientWithResponsesInterface_PostUpdatesWithResponse_Call{Call: _e.mock.On("PostUpdatesWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithResponse_Call) Run(run func(ctx context.Context, body client.LinkUpdate, reqEditors ...client.RequestEditorFn)) *ClientWithResponsesInterface_PostUpdatesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(client.LinkUpdate), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithResponse_Call) Return(_a0 *client.PostUpdatesResponse, _a1 error) *ClientWithResponsesInterface_PostUpdatesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_PostUpdatesWithResponse_Call) RunAndReturn(run func(context.Context, client.LinkUpdate, ...client.RequestEditorFn) (*client.PostUpdatesResponse, error)) *ClientWithResponsesInterface_PostUpdatesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
