// Code generated by mockery v2.52.4. DO NOT EDIT.

package mockRepository

import (
	domain "github.com/central-university-dev/go-z0tedd/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AddSubscription provides a mock function with given fields: userID, sub, subPreferences
func (_m *Repository) AddSubscription(userID int64, sub domain.Subscription, subPreferences domain.UserPreferences) error {
	ret := _m.Called(userID, sub, subPreferences)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, domain.Subscription, domain.UserPreferences) error); ok {
		r0 = rf(userID, sub, subPreferences)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type Repository_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - userID int64
//   - sub domain.Subscription
//   - subPreferences domain.UserPreferences
func (_e *Repository_Expecter) AddSubscription(userID interface{}, sub interface{}, subPreferences interface{}) *Repository_AddSubscription_Call {
	return &Repository_AddSubscription_Call{Call: _e.mock.On("AddSubscription", userID, sub, subPreferences)}
}

func (_c *Repository_AddSubscription_Call) Run(run func(userID int64, sub domain.Subscription, subPreferences domain.UserPreferences)) *Repository_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Subscription), args[2].(domain.UserPreferences))
	})
	return _c
}

func (_c *Repository_AddSubscription_Call) Return(_a0 error) *Repository_AddSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AddSubscription_Call) RunAndReturn(run func(int64, domain.Subscription, domain.UserPreferences) error) *Repository_AddSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: userID
func (_m *Repository) DeleteUser(userID int64) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Repository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) DeleteUser(userID interface{}) *Repository_DeleteUser_Call {
	return &Repository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userID)}
}

func (_c *Repository_DeleteUser_Call) Run(run func(userID int64)) *Repository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_DeleteUser_Call) Return(_a0 error) *Repository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteUser_Call) RunAndReturn(run func(int64) error) *Repository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubsID provides a mock function with no fields
func (_m *Repository) GetSubsID() domain.Set {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubsID")
	}

	var r0 domain.Set
	if rf, ok := ret.Get(0).(func() domain.Set); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Set)
		}
	}

	return r0
}

// Repository_GetSubsID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubsID'
type Repository_GetSubsID_Call struct {
	*mock.Call
}

// GetSubsID is a helper method to define mock.On call
func (_e *Repository_Expecter) GetSubsID() *Repository_GetSubsID_Call {
	return &Repository_GetSubsID_Call{Call: _e.mock.On("GetSubsID")}
}

func (_c *Repository_GetSubsID_Call) Run(run func()) *Repository_GetSubsID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetSubsID_Call) Return(_a0 domain.Set) *Repository_GetSubsID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetSubsID_Call) RunAndReturn(run func() domain.Set) *Repository_GetSubsID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscription provides a mock function with given fields: subID
func (_m *Repository) GetSubscription(subID int64) (domain.Subscription, error) {
	ret := _m.Called(subID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (domain.Subscription, error)); ok {
		return rf(subID)
	}
	if rf, ok := ret.Get(0).(func(int64) domain.Subscription); ok {
		r0 = rf(subID)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(subID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type Repository_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - subID int64
func (_e *Repository_Expecter) GetSubscription(subID interface{}) *Repository_GetSubscription_Call {
	return &Repository_GetSubscription_Call{Call: _e.mock.On("GetSubscription", subID)}
}

func (_c *Repository_GetSubscription_Call) Run(run func(subID int64)) *Repository_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_GetSubscription_Call) Return(_a0 domain.Subscription, _a1 error) *Repository_GetSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSubscription_Call) RunAndReturn(run func(int64) (domain.Subscription, error)) *Repository_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsForUser provides a mock function with given fields: tgChatID
func (_m *Repository) GetSubscriptionsForUser(tgChatID int64) ([]domain.UserPreferences, error) {
	ret := _m.Called(tgChatID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsForUser")
	}

	var r0 []domain.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.UserPreferences, error)); ok {
		return rf(tgChatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.UserPreferences); ok {
		r0 = rf(tgChatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(tgChatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSubscriptionsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsForUser'
type Repository_GetSubscriptionsForUser_Call struct {
	*mock.Call
}

// GetSubscriptionsForUser is a helper method to define mock.On call
//   - tgChatID int64
func (_e *Repository_Expecter) GetSubscriptionsForUser(tgChatID interface{}) *Repository_GetSubscriptionsForUser_Call {
	return &Repository_GetSubscriptionsForUser_Call{Call: _e.mock.On("GetSubscriptionsForUser", tgChatID)}
}

func (_c *Repository_GetSubscriptionsForUser_Call) Run(run func(tgChatID int64)) *Repository_GetSubscriptionsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_GetSubscriptionsForUser_Call) Return(_a0 []domain.UserPreferences, _a1 error) *Repository_GetSubscriptionsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSubscriptionsForUser_Call) RunAndReturn(run func(int64) ([]domain.UserPreferences, error)) *Repository_GetSubscriptionsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: userID
func (_m *Repository) RegisterUser(userID int64) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type Repository_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) RegisterUser(userID interface{}) *Repository_RegisterUser_Call {
	return &Repository_RegisterUser_Call{Call: _e.mock.On("RegisterUser", userID)}
}

func (_c *Repository_RegisterUser_Call) Run(run func(userID int64)) *Repository_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_RegisterUser_Call) Return(_a0 error) *Repository_RegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RegisterUser_Call) RunAndReturn(run func(int64) error) *Repository_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscription provides a mock function with given fields: userID, link
func (_m *Repository) RemoveSubscription(userID int64, link string) error {
	ret := _m.Called(userID, link)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(userID, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type Repository_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - userID int64
//   - link string
func (_e *Repository_Expecter) RemoveSubscription(userID interface{}, link interface{}) *Repository_RemoveSubscription_Call {
	return &Repository_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", userID, link)}
}

func (_c *Repository_RemoveSubscription_Call) Run(run func(userID int64, link string)) *Repository_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Repository_RemoveSubscription_Call) Return(_a0 error) *Repository_RemoveSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RemoveSubscription_Call) RunAndReturn(run func(int64, string) error) *Repository_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscription provides a mock function with given fields: subID, newSub
func (_m *Repository) UpdateSubscription(subID int64, newSub *domain.Subscription) error {
	ret := _m.Called(subID, newSub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *domain.Subscription) error); ok {
		r0 = rf(subID, newSub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscription'
type Repository_UpdateSubscription_Call struct {
	*mock.Call
}

// UpdateSubscription is a helper method to define mock.On call
//   - subID int64
//   - newSub *domain.Subscription
func (_e *Repository_Expecter) UpdateSubscription(subID interface{}, newSub interface{}) *Repository_UpdateSubscription_Call {
	return &Repository_UpdateSubscription_Call{Call: _e.mock.On("UpdateSubscription", subID, newSub)}
}

func (_c *Repository_UpdateSubscription_Call) Run(run func(subID int64, newSub *domain.Subscription)) *Repository_UpdateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*domain.Subscription))
	})
	return _c
}

func (_c *Repository_UpdateSubscription_Call) Return(_a0 error) *Repository_UpdateSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSubscription_Call) RunAndReturn(run func(int64, *domain.Subscription) error) *Repository_UpdateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscriptionActivity provides a mock function with given fields: subID, newActivity
func (_m *Repository) UpdateSubscriptionActivity(subID int64, newActivity domain.Activity) error {
	ret := _m.Called(subID, newActivity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscriptionActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, domain.Activity) error); ok {
		r0 = rf(subID, newActivity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateSubscriptionActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscriptionActivity'
type Repository_UpdateSubscriptionActivity_Call struct {
	*mock.Call
}

// UpdateSubscriptionActivity is a helper method to define mock.On call
//   - subID int64
//   - newActivity domain.Activity
func (_e *Repository_Expecter) UpdateSubscriptionActivity(subID interface{}, newActivity interface{}) *Repository_UpdateSubscriptionActivity_Call {
	return &Repository_UpdateSubscriptionActivity_Call{Call: _e.mock.On("UpdateSubscriptionActivity", subID, newActivity)}
}

func (_c *Repository_UpdateSubscriptionActivity_Call) Run(run func(subID int64, newActivity domain.Activity)) *Repository_UpdateSubscriptionActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Activity))
	})
	return _c
}

func (_c *Repository_UpdateSubscriptionActivity_Call) Return(_a0 error) *Repository_UpdateSubscriptionActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateSubscriptionActivity_Call) RunAndReturn(run func(int64, domain.Activity) error) *Repository_UpdateSubscriptionActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
