// Code generated by mockery v2.52.4. DO NOT EDIT.

package mockRepository

import (
	domain "github.com/central-university-dev/go-z0tedd/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AddSubscription provides a mock function with given fields: userID, link
func (_m *Repository) AddSubscription(userID int64, link string) {
	_m.Called(userID, link)
}

// Repository_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type Repository_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - userID int64
//   - link string
func (_e *Repository_Expecter) AddSubscription(userID interface{}, link interface{}) *Repository_AddSubscription_Call {
	return &Repository_AddSubscription_Call{Call: _e.mock.On("AddSubscription", userID, link)}
}

func (_c *Repository_AddSubscription_Call) Run(run func(userID int64, link string)) *Repository_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Repository_AddSubscription_Call) Return() *Repository_AddSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_AddSubscription_Call) RunAndReturn(run func(int64, string)) *Repository_AddSubscription_Call {
	_c.Run(run)
	return _c
}

// DeleteUser provides a mock function with given fields: userID
func (_m *Repository) DeleteUser(userID int64) {
	_m.Called(userID)
}

// Repository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Repository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) DeleteUser(userID interface{}) *Repository_DeleteUser_Call {
	return &Repository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userID)}
}

func (_c *Repository_DeleteUser_Call) Run(run func(userID int64)) *Repository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_DeleteUser_Call) Return() *Repository_DeleteUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_DeleteUser_Call) RunAndReturn(run func(int64)) *Repository_DeleteUser_Call {
	_c.Run(run)
	return _c
}

// GetState provides a mock function with given fields: userID
func (_m *Repository) GetState(userID int64) string {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Repository_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type Repository_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) GetState(userID interface{}) *Repository_GetState_Call {
	return &Repository_GetState_Call{Call: _e.mock.On("GetState", userID)}
}

func (_c *Repository_GetState_Call) Run(run func(userID int64)) *Repository_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_GetState_Call) Return(_a0 string) *Repository_GetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetState_Call) RunAndReturn(run func(int64) string) *Repository_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsByUserIDs provides a mock function with no fields
func (_m *Repository) GetSubscriptionsByUserIDs() map[*domain.Subscription][]int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsByUserIDs")
	}

	var r0 map[*domain.Subscription][]int64
	if rf, ok := ret.Get(0).(func() map[*domain.Subscription][]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[*domain.Subscription][]int64)
		}
	}

	return r0
}

// Repository_GetSubscriptionsByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsByUserIDs'
type Repository_GetSubscriptionsByUserIDs_Call struct {
	*mock.Call
}

// GetSubscriptionsByUserIDs is a helper method to define mock.On call
func (_e *Repository_Expecter) GetSubscriptionsByUserIDs() *Repository_GetSubscriptionsByUserIDs_Call {
	return &Repository_GetSubscriptionsByUserIDs_Call{Call: _e.mock.On("GetSubscriptionsByUserIDs")}
}

func (_c *Repository_GetSubscriptionsByUserIDs_Call) Run(run func()) *Repository_GetSubscriptionsByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetSubscriptionsByUserIDs_Call) Return(_a0 map[*domain.Subscription][]int64) *Repository_GetSubscriptionsByUserIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetSubscriptionsByUserIDs_Call) RunAndReturn(run func() map[*domain.Subscription][]int64) *Repository_GetSubscriptionsByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function with given fields: userID
func (_m *Repository) GetTags(userID int64) *[]string {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 *[]string
	if rf, ok := ret.Get(0).(func(int64) *[]string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}

	return r0
}

// Repository_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type Repository_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) GetTags(userID interface{}) *Repository_GetTags_Call {
	return &Repository_GetTags_Call{Call: _e.mock.On("GetTags", userID)}
}

func (_c *Repository_GetTags_Call) Run(run func(userID int64)) *Repository_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_GetTags_Call) Return(_a0 *[]string) *Repository_GetTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetTags_Call) RunAndReturn(run func(int64) *[]string) *Repository_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithSubs provides a mock function with no fields
func (_m *Repository) GetUsersWithSubs() map[int64][]*domain.Subscription {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithSubs")
	}

	var r0 map[int64][]*domain.Subscription
	if rf, ok := ret.Get(0).(func() map[int64][]*domain.Subscription); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64][]*domain.Subscription)
		}
	}

	return r0
}

// Repository_GetUsersWithSubs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithSubs'
type Repository_GetUsersWithSubs_Call struct {
	*mock.Call
}

// GetUsersWithSubs is a helper method to define mock.On call
func (_e *Repository_Expecter) GetUsersWithSubs() *Repository_GetUsersWithSubs_Call {
	return &Repository_GetUsersWithSubs_Call{Call: _e.mock.On("GetUsersWithSubs")}
}

func (_c *Repository_GetUsersWithSubs_Call) Run(run func()) *Repository_GetUsersWithSubs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetUsersWithSubs_Call) Return(_a0 map[int64][]*domain.Subscription) *Repository_GetUsersWithSubs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_GetUsersWithSubs_Call) RunAndReturn(run func() map[int64][]*domain.Subscription) *Repository_GetUsersWithSubs_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubscriptions provides a mock function with given fields: userID
func (_m *Repository) ListSubscriptions(userID int64) []*domain.Subscription {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscriptions")
	}

	var r0 []*domain.Subscription
	if rf, ok := ret.Get(0).(func(int64) []*domain.Subscription); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Subscription)
		}
	}

	return r0
}

// Repository_ListSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubscriptions'
type Repository_ListSubscriptions_Call struct {
	*mock.Call
}

// ListSubscriptions is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) ListSubscriptions(userID interface{}) *Repository_ListSubscriptions_Call {
	return &Repository_ListSubscriptions_Call{Call: _e.mock.On("ListSubscriptions", userID)}
}

func (_c *Repository_ListSubscriptions_Call) Run(run func(userID int64)) *Repository_ListSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_ListSubscriptions_Call) Return(_a0 []*domain.Subscription) *Repository_ListSubscriptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_ListSubscriptions_Call) RunAndReturn(run func(int64) []*domain.Subscription) *Repository_ListSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: userID
func (_m *Repository) RegisterUser(userID int64) {
	_m.Called(userID)
}

// Repository_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type Repository_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - userID int64
func (_e *Repository_Expecter) RegisterUser(userID interface{}) *Repository_RegisterUser_Call {
	return &Repository_RegisterUser_Call{Call: _e.mock.On("RegisterUser", userID)}
}

func (_c *Repository_RegisterUser_Call) Run(run func(userID int64)) *Repository_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Repository_RegisterUser_Call) Return() *Repository_RegisterUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_RegisterUser_Call) RunAndReturn(run func(int64)) *Repository_RegisterUser_Call {
	_c.Run(run)
	return _c
}

// RemoveSubscription provides a mock function with given fields: userID, link
func (_m *Repository) RemoveSubscription(userID int64, link string) bool {
	ret := _m.Called(userID, link)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, string) bool); ok {
		r0 = rf(userID, link)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Repository_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type Repository_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - userID int64
//   - link string
func (_e *Repository_Expecter) RemoveSubscription(userID interface{}, link interface{}) *Repository_RemoveSubscription_Call {
	return &Repository_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", userID, link)}
}

func (_c *Repository_RemoveSubscription_Call) Run(run func(userID int64, link string)) *Repository_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Repository_RemoveSubscription_Call) Return(_a0 bool) *Repository_RemoveSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RemoveSubscription_Call) RunAndReturn(run func(int64, string) bool) *Repository_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// SetFilters provides a mock function with given fields: userID, filters
func (_m *Repository) SetFilters(userID int64, filters map[string]string) {
	_m.Called(userID, filters)
}

// Repository_SetFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFilters'
type Repository_SetFilters_Call struct {
	*mock.Call
}

// SetFilters is a helper method to define mock.On call
//   - userID int64
//   - filters map[string]string
func (_e *Repository_Expecter) SetFilters(userID interface{}, filters interface{}) *Repository_SetFilters_Call {
	return &Repository_SetFilters_Call{Call: _e.mock.On("SetFilters", userID, filters)}
}

func (_c *Repository_SetFilters_Call) Run(run func(userID int64, filters map[string]string)) *Repository_SetFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(map[string]string))
	})
	return _c
}

func (_c *Repository_SetFilters_Call) Return() *Repository_SetFilters_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_SetFilters_Call) RunAndReturn(run func(int64, map[string]string)) *Repository_SetFilters_Call {
	_c.Run(run)
	return _c
}

// SetState provides a mock function with given fields: userID, state
func (_m *Repository) SetState(userID int64, state string) {
	_m.Called(userID, state)
}

// Repository_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type Repository_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - userID int64
//   - state string
func (_e *Repository_Expecter) SetState(userID interface{}, state interface{}) *Repository_SetState_Call {
	return &Repository_SetState_Call{Call: _e.mock.On("SetState", userID, state)}
}

func (_c *Repository_SetState_Call) Run(run func(userID int64, state string)) *Repository_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Repository_SetState_Call) Return() *Repository_SetState_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_SetState_Call) RunAndReturn(run func(int64, string)) *Repository_SetState_Call {
	_c.Run(run)
	return _c
}

// SetTags provides a mock function with given fields: userID, tags
func (_m *Repository) SetTags(userID int64, tags []string) {
	_m.Called(userID, tags)
}

// Repository_SetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTags'
type Repository_SetTags_Call struct {
	*mock.Call
}

// SetTags is a helper method to define mock.On call
//   - userID int64
//   - tags []string
func (_e *Repository_Expecter) SetTags(userID interface{}, tags interface{}) *Repository_SetTags_Call {
	return &Repository_SetTags_Call{Call: _e.mock.On("SetTags", userID, tags)}
}

func (_c *Repository_SetTags_Call) Run(run func(userID int64, tags []string)) *Repository_SetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].([]string))
	})
	return _c
}

func (_c *Repository_SetTags_Call) Return() *Repository_SetTags_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_SetTags_Call) RunAndReturn(run func(int64, []string)) *Repository_SetTags_Call {
	_c.Run(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
