// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ActivityEvent defines model for ActivityEvent.
type ActivityEvent struct {
	ActivityType *string    `json:"activity_type,omitempty"`
	Actor        *User      `json:"actor,omitempty"`
	After        *string    `json:"after,omitempty"`
	Before       *string    `json:"before,omitempty"`
	Id           *string    `json:"id,omitempty"`
	Timestamp    *time.Time `json:"timestamp,omitempty"`
}

// Commit defines model for Commit.
type Commit struct {
	Commit *struct {
		Author *struct {
			Date *time.Time `json:"date,omitempty"`
			Name *string    `json:"name,omitempty"`
		} `json:"author,omitempty"`
		Committer *struct {
			Date *time.Time `json:"date,omitempty"`
			Name *string    `json:"name,omitempty"`
		} `json:"committer,omitempty"`
		Message *string `json:"message,omitempty"`
		Url     *string `json:"url,omitempty"`
	} `json:"commit,omitempty"`
	Sha *string `json:"sha,omitempty"`
}

// Repository defines model for Repository.
type Repository struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	FullName    *string    `json:"full_name,omitempty"`
	HtmlUrl     *string    `json:"html_url,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Owner       *User      `json:"owner,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string    `json:"avatar_url,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	HtmlUrl   *string    `json:"html_url,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Login     *string    `json:"login,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// OwnerParam defines model for ownerParam.
type OwnerParam = string

// RepoParam defines model for repoParam.
type RepoParam = string

// UsernameParam defines model for usernameParam.
type UsernameParam = string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetReposOwnerRepo request
	GetReposOwnerRepo(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReposOwnerRepoActivity request
	GetReposOwnerRepoActivity(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReposOwnerRepoCommits request
	GetReposOwnerRepoCommits(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUsername request
	GetUsersUsername(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUsernameRepos request
	GetUsersUsernameRepos(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetReposOwnerRepo(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReposOwnerRepoRequest(c.Server, owner, repo)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReposOwnerRepoActivity(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReposOwnerRepoActivityRequest(c.Server, owner, repo)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReposOwnerRepoCommits(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReposOwnerRepoCommitsRequest(c.Server, owner, repo)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUsername(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUsernameRequest(c.Server, username)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUsernameRepos(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUsernameReposRequest(c.Server, username)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetReposOwnerRepoRequest generates requests for GetReposOwnerRepo
func NewGetReposOwnerRepoRequest(server string, owner OwnerParam, repo RepoParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "owner", runtime.ParamLocationPath, owner)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repo", runtime.ParamLocationPath, repo)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repos/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReposOwnerRepoActivityRequest generates requests for GetReposOwnerRepoActivity
func NewGetReposOwnerRepoActivityRequest(server string, owner OwnerParam, repo RepoParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "owner", runtime.ParamLocationPath, owner)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repo", runtime.ParamLocationPath, repo)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repos/%s/%s/activity", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReposOwnerRepoCommitsRequest generates requests for GetReposOwnerRepoCommits
func NewGetReposOwnerRepoCommitsRequest(server string, owner OwnerParam, repo RepoParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "owner", runtime.ParamLocationPath, owner)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "repo", runtime.ParamLocationPath, repo)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repos/%s/%s/commits", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUsernameRequest generates requests for GetUsersUsername
func NewGetUsersUsernameRequest(server string, username UsernameParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "username", runtime.ParamLocationPath, username)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUsernameReposRequest generates requests for GetUsersUsernameRepos
func NewGetUsersUsernameReposRequest(server string, username UsernameParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "username", runtime.ParamLocationPath, username)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/repos", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetReposOwnerRepoWithResponse request
	GetReposOwnerRepoWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoResponse, error)

	// GetReposOwnerRepoActivityWithResponse request
	GetReposOwnerRepoActivityWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoActivityResponse, error)

	// GetReposOwnerRepoCommitsWithResponse request
	GetReposOwnerRepoCommitsWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoCommitsResponse, error)

	// GetUsersUsernameWithResponse request
	GetUsersUsernameWithResponse(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*GetUsersUsernameResponse, error)

	// GetUsersUsernameReposWithResponse request
	GetUsersUsernameReposWithResponse(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*GetUsersUsernameReposResponse, error)
}

type GetReposOwnerRepoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Repository
}

// Status returns HTTPResponse.Status
func (r GetReposOwnerRepoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReposOwnerRepoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReposOwnerRepoActivityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ActivityEvent
}

// Status returns HTTPResponse.Status
func (r GetReposOwnerRepoActivityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReposOwnerRepoActivityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReposOwnerRepoCommitsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Commit
}

// Status returns HTTPResponse.Status
func (r GetReposOwnerRepoCommitsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReposOwnerRepoCommitsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUsernameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetUsersUsernameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUsernameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUsernameReposResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Repository
}

// Status returns HTTPResponse.Status
func (r GetUsersUsernameReposResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUsernameReposResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetReposOwnerRepoWithResponse request returning *GetReposOwnerRepoResponse
func (c *ClientWithResponses) GetReposOwnerRepoWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoResponse, error) {
	rsp, err := c.GetReposOwnerRepo(ctx, owner, repo, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReposOwnerRepoResponse(rsp)
}

// GetReposOwnerRepoActivityWithResponse request returning *GetReposOwnerRepoActivityResponse
func (c *ClientWithResponses) GetReposOwnerRepoActivityWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoActivityResponse, error) {
	rsp, err := c.GetReposOwnerRepoActivity(ctx, owner, repo, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReposOwnerRepoActivityResponse(rsp)
}

// GetReposOwnerRepoCommitsWithResponse request returning *GetReposOwnerRepoCommitsResponse
func (c *ClientWithResponses) GetReposOwnerRepoCommitsWithResponse(ctx context.Context, owner OwnerParam, repo RepoParam, reqEditors ...RequestEditorFn) (*GetReposOwnerRepoCommitsResponse, error) {
	rsp, err := c.GetReposOwnerRepoCommits(ctx, owner, repo, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReposOwnerRepoCommitsResponse(rsp)
}

// GetUsersUsernameWithResponse request returning *GetUsersUsernameResponse
func (c *ClientWithResponses) GetUsersUsernameWithResponse(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*GetUsersUsernameResponse, error) {
	rsp, err := c.GetUsersUsername(ctx, username, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUsernameResponse(rsp)
}

// GetUsersUsernameReposWithResponse request returning *GetUsersUsernameReposResponse
func (c *ClientWithResponses) GetUsersUsernameReposWithResponse(ctx context.Context, username UsernameParam, reqEditors ...RequestEditorFn) (*GetUsersUsernameReposResponse, error) {
	rsp, err := c.GetUsersUsernameRepos(ctx, username, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUsernameReposResponse(rsp)
}

// ParseGetReposOwnerRepoResponse parses an HTTP response from a GetReposOwnerRepoWithResponse call
func ParseGetReposOwnerRepoResponse(rsp *http.Response) (*GetReposOwnerRepoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReposOwnerRepoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetReposOwnerRepoActivityResponse parses an HTTP response from a GetReposOwnerRepoActivityWithResponse call
func ParseGetReposOwnerRepoActivityResponse(rsp *http.Response) (*GetReposOwnerRepoActivityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReposOwnerRepoActivityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ActivityEvent
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetReposOwnerRepoCommitsResponse parses an HTTP response from a GetReposOwnerRepoCommitsWithResponse call
func ParseGetReposOwnerRepoCommitsResponse(rsp *http.Response) (*GetReposOwnerRepoCommitsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReposOwnerRepoCommitsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Commit
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUsersUsernameResponse parses an HTTP response from a GetUsersUsernameWithResponse call
func ParseGetUsersUsernameResponse(rsp *http.Response) (*GetUsersUsernameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUsernameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUsersUsernameReposResponse parses an HTTP response from a GetUsersUsernameReposWithResponse call
func ParseGetUsersUsernameReposResponse(rsp *http.Response) (*GetUsersUsernameReposResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUsernameReposResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Repository
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
