// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OrderParam.
const (
	OrderParamAsc  OrderParam = "asc"
	OrderParamDesc OrderParam = "desc"
)

// Defines values for SiteParam.
const (
	SiteParamStackexchange SiteParam = "stackexchange"
	SiteParamStackoverflow SiteParam = "stackoverflow"
)

// Defines values for SortParam.
const (
	SortParamActivity SortParam = "activity"
	SortParamCreation SortParam = "creation"
	SortParamVotes    SortParam = "votes"
)

// Defines values for GetQuestionsByIdsParamsOrder.
const (
	GetQuestionsByIdsParamsOrderAsc  GetQuestionsByIdsParamsOrder = "asc"
	GetQuestionsByIdsParamsOrderDesc GetQuestionsByIdsParamsOrder = "desc"
)

// Defines values for GetQuestionsByIdsParamsSort.
const (
	GetQuestionsByIdsParamsSortActivity GetQuestionsByIdsParamsSort = "activity"
	GetQuestionsByIdsParamsSortCreation GetQuestionsByIdsParamsSort = "creation"
	GetQuestionsByIdsParamsSortVotes    GetQuestionsByIdsParamsSort = "votes"
)

// Defines values for GetQuestionsByIdsParamsSite.
const (
	GetQuestionsByIdsParamsSiteStackexchange GetQuestionsByIdsParamsSite = "stackexchange"
	GetQuestionsByIdsParamsSiteStackoverflow GetQuestionsByIdsParamsSite = "stackoverflow"
)

// Defines values for GetQuestionAnswersParamsOrder.
const (
	Asc  GetQuestionAnswersParamsOrder = "asc"
	Desc GetQuestionAnswersParamsOrder = "desc"
)

// Defines values for GetQuestionAnswersParamsSort.
const (
	Activity GetQuestionAnswersParamsSort = "activity"
	Creation GetQuestionAnswersParamsSort = "creation"
	Votes    GetQuestionAnswersParamsSort = "votes"
)

// Defines values for GetQuestionAnswersParamsSite.
const (
	Stackexchange GetQuestionAnswersParamsSite = "stackexchange"
	Stackoverflow GetQuestionAnswersParamsSite = "stackoverflow"
)

// Answer defines model for Answer.
type Answer struct {
	AnswerId         *int    `json:"answer_id,omitempty"`
	ContentLicense   *string `json:"content_license,omitempty"`
	CreationDate     *int    `json:"creation_date,omitempty"`
	IsAccepted       *bool   `json:"is_accepted,omitempty"`
	LastActivityDate *int    `json:"last_activity_date,omitempty"`
	LastEditDate     *int    `json:"last_edit_date,omitempty"`
	Owner            *User   `json:"owner,omitempty"`
	QuestionId       *int    `json:"question_id,omitempty"`
	Score            *int    `json:"score,omitempty"`
}

// Question defines model for Question.
type Question struct {
	AcceptedAnswerId *int      `json:"accepted_answer_id,omitempty"`
	AnswerCount      *int      `json:"answer_count,omitempty"`
	ClosedDate       *int      `json:"closed_date,omitempty"`
	ClosedReason     *string   `json:"closed_reason,omitempty"`
	ContentLicense   *string   `json:"content_license,omitempty"`
	CreationDate     *int      `json:"creation_date,omitempty"`
	IsAnswered       *bool     `json:"is_answered,omitempty"`
	LastActivityDate *int      `json:"last_activity_date,omitempty"`
	LastEditDate     *int      `json:"last_edit_date,omitempty"`
	Link             *string   `json:"link,omitempty"`
	Owner            *User     `json:"owner,omitempty"`
	ProtectedDate    *int      `json:"protected_date,omitempty"`
	QuestionId       *int      `json:"question_id,omitempty"`
	Score            *int      `json:"score,omitempty"`
	Tags             *[]string `json:"tags,omitempty"`
	Title            *string   `json:"title,omitempty"`
	ViewCount        *int      `json:"view_count,omitempty"`
}

// User defines model for User.
type User struct {
	AcceptRate   *int    `json:"accept_rate,omitempty"`
	AccountId    *int    `json:"account_id,omitempty"`
	DisplayName  *string `json:"display_name,omitempty"`
	Link         *string `json:"link,omitempty"`
	ProfileImage *string `json:"profile_image,omitempty"`
	Reputation   *int    `json:"reputation,omitempty"`
	UserId       *int    `json:"user_id,omitempty"`
	UserType     *string `json:"user_type,omitempty"`
}

// FromDateParam defines model for FromDateParam.
type FromDateParam = int

// IdParam defines model for IdParam.
type IdParam = string

// MaxParam defines model for MaxParam.
type MaxParam = int

// MinParam defines model for MinParam.
type MinParam = int

// OrderParam defines model for OrderParam.
type OrderParam string

// PageParam defines model for PageParam.
type PageParam = int

// PagesizeParam defines model for PagesizeParam.
type PagesizeParam = int

// SiteParam defines model for SiteParam.
type SiteParam string

// SortParam defines model for SortParam.
type SortParam string

// ToDateParam defines model for ToDateParam.
type ToDateParam = int

// GetQuestionsByIdsParams defines parameters for GetQuestionsByIds.
type GetQuestionsByIdsParams struct {
	// Order The order of sorting (e.g., "desc" or "asc").
	Order *GetQuestionsByIdsParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Sort The field to sort by (e.g., "activity", "creation", "votes").
	Sort *GetQuestionsByIdsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Site The Stack Exchange site to query (e.g., "stackoverflow").
	Site GetQuestionsByIdsParamsSite `form:"site" json:"site"`

	// Page The page number for paginated results.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Pagesize The number of items per page.
	Pagesize *PagesizeParam `form:"pagesize,omitempty" json:"pagesize,omitempty"`

	// Fromdate Start date for filtering results (Unix epoch time).
	Fromdate *FromDateParam `form:"fromdate,omitempty" json:"fromdate,omitempty"`

	// Todate End date for filtering results (Unix epoch time).
	Todate *ToDateParam `form:"todate,omitempty" json:"todate,omitempty"`

	// Min Minimum value for the sort field.
	Min *MinParam `form:"min,omitempty" json:"min,omitempty"`

	// Max Maximum value for the sort field.
	Max *MaxParam `form:"max,omitempty" json:"max,omitempty"`
}

// GetQuestionsByIdsParamsOrder defines parameters for GetQuestionsByIds.
type GetQuestionsByIdsParamsOrder string

// GetQuestionsByIdsParamsSort defines parameters for GetQuestionsByIds.
type GetQuestionsByIdsParamsSort string

// GetQuestionsByIdsParamsSite defines parameters for GetQuestionsByIds.
type GetQuestionsByIdsParamsSite string

// GetQuestionAnswersParams defines parameters for GetQuestionAnswers.
type GetQuestionAnswersParams struct {
	// Order The order of sorting (e.g., "desc" or "asc").
	Order *GetQuestionAnswersParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Sort The field to sort by (e.g., "activity", "creation", "votes").
	Sort *GetQuestionAnswersParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Site The Stack Exchange site to query (e.g., "stackoverflow").
	Site GetQuestionAnswersParamsSite `form:"site" json:"site"`

	// Page The page number for paginated results.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Pagesize The number of items per page.
	Pagesize *PagesizeParam `form:"pagesize,omitempty" json:"pagesize,omitempty"`

	// Fromdate Start date for filtering results (Unix epoch time).
	Fromdate *FromDateParam `form:"fromdate,omitempty" json:"fromdate,omitempty"`

	// Todate End date for filtering results (Unix epoch time).
	Todate *ToDateParam `form:"todate,omitempty" json:"todate,omitempty"`

	// Min Minimum value for the sort field.
	Min *MinParam `form:"min,omitempty" json:"min,omitempty"`

	// Max Maximum value for the sort field.
	Max *MaxParam `form:"max,omitempty" json:"max,omitempty"`
}

// GetQuestionAnswersParamsOrder defines parameters for GetQuestionAnswers.
type GetQuestionAnswersParamsOrder string

// GetQuestionAnswersParamsSort defines parameters for GetQuestionAnswers.
type GetQuestionAnswersParamsSort string

// GetQuestionAnswersParamsSite defines parameters for GetQuestionAnswers.
type GetQuestionAnswersParamsSite string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetQuestionsByIds request
	GetQuestionsByIds(ctx context.Context, ids IdParam, params *GetQuestionsByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQuestionAnswers request
	GetQuestionAnswers(ctx context.Context, ids IdParam, params *GetQuestionAnswersParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetQuestionsByIds(ctx context.Context, ids IdParam, params *GetQuestionsByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQuestionsByIdsRequest(c.Server, ids, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQuestionAnswers(ctx context.Context, ids IdParam, params *GetQuestionAnswersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQuestionAnswersRequest(c.Server, ids, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetQuestionsByIdsRequest generates requests for GetQuestionsByIds
func NewGetQuestionsByIdsRequest(server string, ids IdParam, params *GetQuestionsByIdsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "ids", runtime.ParamLocationPath, ids)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/questions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "site", runtime.ParamLocationQuery, params.Site); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Pagesize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pagesize", runtime.ParamLocationQuery, *params.Pagesize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fromdate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fromdate", runtime.ParamLocationQuery, *params.Fromdate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Todate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "todate", runtime.ParamLocationQuery, *params.Todate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Min != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "min", runtime.ParamLocationQuery, *params.Min); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Max != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "max", runtime.ParamLocationQuery, *params.Max); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetQuestionAnswersRequest generates requests for GetQuestionAnswers
func NewGetQuestionAnswersRequest(server string, ids IdParam, params *GetQuestionAnswersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "ids", runtime.ParamLocationPath, ids)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/questions/%s/answers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "site", runtime.ParamLocationQuery, params.Site); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Pagesize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pagesize", runtime.ParamLocationQuery, *params.Pagesize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fromdate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fromdate", runtime.ParamLocationQuery, *params.Fromdate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Todate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "todate", runtime.ParamLocationQuery, *params.Todate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Min != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "min", runtime.ParamLocationQuery, *params.Min); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Max != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "max", runtime.ParamLocationQuery, *params.Max); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetQuestionsByIdsWithResponse request
	GetQuestionsByIdsWithResponse(ctx context.Context, ids IdParam, params *GetQuestionsByIdsParams, reqEditors ...RequestEditorFn) (*GetQuestionsByIdsResponse, error)

	// GetQuestionAnswersWithResponse request
	GetQuestionAnswersWithResponse(ctx context.Context, ids IdParam, params *GetQuestionAnswersParams, reqEditors ...RequestEditorFn) (*GetQuestionAnswersResponse, error)
}

type GetQuestionsByIdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		HasMore        *bool       `json:"has_more,omitempty"`
		Items          *[]Question `json:"items,omitempty"`
		QuotaMax       *int        `json:"quota_max,omitempty"`
		QuotaRemaining *int        `json:"quota_remaining,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetQuestionsByIdsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQuestionsByIdsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetQuestionAnswersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		HasMore        *bool     `json:"has_more,omitempty"`
		Items          *[]Answer `json:"items,omitempty"`
		QuotaMax       *int      `json:"quota_max,omitempty"`
		QuotaRemaining *int      `json:"quota_remaining,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetQuestionAnswersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQuestionAnswersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetQuestionsByIdsWithResponse request returning *GetQuestionsByIdsResponse
func (c *ClientWithResponses) GetQuestionsByIdsWithResponse(ctx context.Context, ids IdParam, params *GetQuestionsByIdsParams, reqEditors ...RequestEditorFn) (*GetQuestionsByIdsResponse, error) {
	rsp, err := c.GetQuestionsByIds(ctx, ids, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQuestionsByIdsResponse(rsp)
}

// GetQuestionAnswersWithResponse request returning *GetQuestionAnswersResponse
func (c *ClientWithResponses) GetQuestionAnswersWithResponse(ctx context.Context, ids IdParam, params *GetQuestionAnswersParams, reqEditors ...RequestEditorFn) (*GetQuestionAnswersResponse, error) {
	rsp, err := c.GetQuestionAnswers(ctx, ids, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQuestionAnswersResponse(rsp)
}

// ParseGetQuestionsByIdsResponse parses an HTTP response from a GetQuestionsByIdsWithResponse call
func ParseGetQuestionsByIdsResponse(rsp *http.Response) (*GetQuestionsByIdsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQuestionsByIdsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			HasMore        *bool       `json:"has_more,omitempty"`
			Items          *[]Question `json:"items,omitempty"`
			QuotaMax       *int        `json:"quota_max,omitempty"`
			QuotaRemaining *int        `json:"quota_remaining,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetQuestionAnswersResponse parses an HTTP response from a GetQuestionAnswersWithResponse call
func ParseGetQuestionAnswersResponse(rsp *http.Response) (*GetQuestionAnswersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQuestionAnswersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			HasMore        *bool     `json:"has_more,omitempty"`
			Items          *[]Answer `json:"items,omitempty"`
			QuotaMax       *int      `json:"quota_max,omitempty"`
			QuotaRemaining *int      `json:"quota_remaining,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
